# Generated by Django 4.0.2 on 2022-05-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.customer')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='DeliveryApp.shipper')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
