# Generated by Django 4.0.3 on 2022-03-23 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='CMND',
        ),
    ]
