# Generated by Django 4.0.2 on 2022-05-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='rate',
            new_name='bid',
        ),
    ]
