# Generated by Django 4.0.2 on 2022-05-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0002_rename_rate_bidding_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='customer',
        ),
    ]
