# Generated by Django 4.0.3 on 2022-03-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0003_shipper_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipper',
        ),
    ]
