# Generated by Django 4.0.3 on 2022-03-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0005_user_is_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iden_no',
            field=models.TextField(default='', max_length=100),
        ),
    ]
