# Generated by Django 4.0.3 on 2022-03-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0006_user_iden_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iden_no',
            field=models.TextField(default='', max_length=100, null=True),
        ),
    ]
