# Generated by Django 4.0.3 on 2022-03-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0007_alter_user_iden_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iden_no',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
