# Generated by Django 4.0.3 on 2022-04-27 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0011_remove_user_iden_no_remove_user_is_shipper_shipper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper',
            name='id',
        ),
        migrations.AlterField(
            model_name='shipper',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
