# Generated by Django 4.0.3 on 2022-04-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0017_remove_order_list_shipper_delete_shipperinbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipperInBid',
            fields=[
                ('shipper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DeliveryApp.shipper')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='list_shipper',
            field=models.ManyToManyField(related_name='order', to='DeliveryApp.shipperinbid'),
        ),
    ]
