# Generated by Django 4.0.3 on 2022-04-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0018_shipperinbid_order_list_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipperinbid',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DeliveryApp.shipper'),
        ),
    ]
