# Generated by Django 4.0.3 on 2022-04-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0020_remove_order_list_shipper_delete_shipperinbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipper',
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DeliveryApp.order')),
                ('price', models.FloatField()),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DeliveryApp.shipper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DeliveryApp.order')),
                ('price', models.FloatField()),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.shipper')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
