# Generated by Django 4.0.3 on 2022-04-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0021_remove_order_shipper_receipt_bidding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bidding',
        ),
    ]
