# Generated by Django 4.0.3 on 2022-04-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0022_delete_bidding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.order')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.shipper')),
            ],
            options={
                'unique_together': {('order', 'shipper')},
            },
        ),
    ]
