# Generated by Django 4.0.3 on 2022-04-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0023_bidding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='order',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='shipper',
        ),
        migrations.DeleteModel(
            name='Bidding',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
